# Generated by Django 3.2.6 on 2021-09-19 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daycare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField()),
                ('parent_name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=40)),
                ('payment_info', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=40)),
                ('Daycare_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bright_demo_app.daycare')),
            ],
        ),
    ]
